"""Unit tests for MCP_Server/docgen.py generated documentation."""

from pathlib import Path

import pytest


class TestDocgenExtraction:
    """Value-asserting tests for docgen tool extraction."""

    def test_extract_all_tools_returns_list(self):
        from MCP_Server.docgen import extract_all_tools
        tools = extract_all_tools()
        assert isinstance(tools, list)
        assert len(tools) > 50

    def test_each_tool_has_name_and_file(self):
        from MCP_Server.docgen import extract_all_tools
        tools = extract_all_tools()
        for t in tools:
            assert "name" in t
            assert "file" in t

    def test_tool_names_unique(self):
        from MCP_Server.docgen import extract_all_tools
        tools = extract_all_tools()
        names = [t["name"] for t in tools]
        assert len(names) == len(set(names)), "Duplicate tool names detected"

    def test_tools_have_params(self):
        from MCP_Server.docgen import extract_all_tools
        tools = extract_all_tools()
        with_params = [t for t in tools if t.get("params")]
        assert len(with_params) > 0

    def test_generate_creates_docs(self):
        from MCP_Server.docgen import extract_all_tools, generate_tools_md, generate_quick_reference_md
        Path("docs").mkdir(exist_ok=True)
        tools = extract_all_tools()
        Path("docs/TOOLS.md").write_text(generate_tools_md(tools), encoding="utf-8")
        Path("docs/QUICK_REFERENCE.md").write_text(generate_quick_reference_md(tools), encoding="utf-8")
        assert Path("docs/TOOLS.md").exists()
        assert Path("docs/QUICK_REFERENCE.md").exists()

    def test_generated_docs_have_banner(self):
        from MCP_Server.docgen import extract_all_tools, generate_tools_md
        tools = extract_all_tools()
        content = generate_tools_md(tools)
        assert "AUTOGENERATED" in content[:500], "Banner missing from first 500 chars"
