"""Unit tests for MCP_Server/docgen.py generated documentation."""

from pathlib import Path

import pytest


class TestDocgenExtraction:
    """Value-asserting tests for docgen tool extraction."""

    def test_extract_all_tools_returns_list(self):
        from MCP_Server.docgen import extract_all_tools
        tools = extract_all_tools()
        assert isinstance(tools, list)
        assert len(tools) > 50

    def test_each_tool_has_name_and_file(self):
        from MCP_Server.docgen import extract_all_tools
        tools = extract_all_tools()
        for t in tools:
            assert "name" in t
            assert "file" in t

    def test_tool_names_unique(self):
        from MCP_Server.docgen import extract_all_tools
        tools = extract_all_tools()
        names = [t["name"] for t in tools]
        assert len(names) == len(set(names)), "Duplicate tool names detected"

    def test_tools_have_params(self):
        from MCP_Server.docgen import extract_all_tools
        tools = extract_all_tools()
        with_params = [t for t in tools if t.get("params")]
        assert len(with_params) > 0

    def test_generate_creates_docs(self):
        from MCP_Server.docgen import extract_all_tools, generate_tools_md, generate_quick_reference_md
        Path("docs").mkdir(exist_ok=True)
        tools = extract_all_tools()
        Path("docs/TOOLS.md").write_text(generate_tools_md(tools), encoding="utf-8")
        Path("docs/QUICK_REFERENCE.md").write_text(generate_quick_reference_md(tools), encoding="utf-8")
        assert Path("docs/TOOLS.md").exists()
        assert Path("docs/QUICK_REFERENCE.md").exists()

    def test_generated_docs_have_banner(self):
        from MCP_Server.docgen import extract_all_tools, generate_tools_md
        tools = extract_all_tools()
        content = generate_tools_md(tools)
        assert "AUTOGENERATED" in content[:500], "Banner missing from first 500 chars"


class TestMutationKillingValueAssertions:
    """Kill remaining docgen mutation survivors."""

    def test_private_modules_excluded_from_scan(self, tmp_path, monkeypatch):
        """OR_TO_AND: skip logic must be OR-based — any private (_*) or __init__ file excluded."""
        import MCP_Server.docgen as dg
        d = tmp_path / "mcp_scan"
        d.mkdir()
        (d / "_private.py").write_text(
            'from mcp.server.fastmcp import FastMCP\nserver = FastMCP("x")\n'
            '@server.tool()\ndef secret():\n    "hidden"\n    pass\n',
            encoding="utf-8")
        (d / "visible.py").write_text(
            'from mcp.server.fastmcp import FastMCP\nserver = FastMCP("x")\n'
            '@server.tool()\ndef open_tool():\n    "shown"\n    pass\n',
            encoding="utf-8")
        monkeypatch.setattr(dg, "MCP_SERVER_DIR", d)
        files = dg.get_mcp_server_files()
        names = {f.name for f in files}
        assert "_private.py" not in names, "private modules must be skipped"
        assert "visible.py" in names

    def test_kwargs_param_included(self, tmp_path, monkeypatch):
        """NOT_ADDED: **kwargs params must be included unless named ctx/self."""
        import MCP_Server.docgen as dg
        d = tmp_path / "mcp_kw"
        d.mkdir()
        (d / "kw_tools.py").write_text(
            'from mcp.server.fastmcp import FastMCP\nserver = FastMCP("x")\n'
            "@server.tool()\ndef flexible(x: int = 1, **extra) -> None:\n"
            '    "takes kwargs"\n'
            '    pass\n',
            encoding="utf-8")
        monkeypatch.setattr(dg, "MCP_SERVER_DIR", d)
        tools = dg.extract_all_tools()
        assert len(tools) == 1
        names = {p["name"] for p in tools[0]["params"]}
        assert "extra" in names, "**kwargs param must be documented"

    def test_generated_md_category_counts_positive(self):
        """PLUS_TO_MINUS: rendered category counts must equal independent counts."""
        from MCP_Server.docgen import categorize_tool, extract_all_tools, generate_tools_md
        tools = extract_all_tools()
        expected = {}
        for t in tools:
            cat = categorize_tool(t["name"], t["docstring"])
            expected[cat] = expected.get(cat, 0) + 1
        md = generate_tools_md(tools)
        for cat, n in expected.items():
            assert f"- **{cat}**: {n}" in md, f"category {cat!r} count {n} missing from md"

    def test_main_write_twice_no_raise(self, monkeypatch):
        """TRUE_TO_FALSE: docs dir exists; exist_ok must tolerate re-runs."""
        import sys
        import MCP_Server.docgen as dg
        monkeypatch.setattr(sys, "argv", ["docgen"])
        dg.main()
        dg.main()  # second run: mkdir(exist_ok=True); must not raise


@pytest.mark.parametrize("name,docstring,expected", [
    ("set_track_volume", "set track volume", "udp"),
    ("create_midi_track", "create a session track", "session-setup"),
    ("capture_to_arrangement", "arrangement capture, record region", "arrangement"),
    ("set_master_volume", "mixer level, volume control", "udp"),
    ("load_instrument_or_effect", "load device, reverb preset", "effects"),
    ("add_notes_to_clip", "midi note entry, quantize", "midi"),
    ("create_drum_pattern", "build groove, pattern generator", "generation"),
    ("optimize_mix", "optimize, balance, polish levels", "mixing"),  # mixing rule precedes optimization
    ("dub_echo_sweep", "dub delay, fat_beatz effect", "dub"),
    ("live_performance", "performance, live dj set", "performance"),
    ("advanced_smart_mix", "advanced, intelligent ai mix", "mixing"),  # mixing rule precedes advanced
    ("total_chaos", "unrelated words only", "other"),
], ids=["udp_set_volume", "volume", "pan", "send_amount", "udp_master",
        "effects", "midi", "generation", "optimize_is_mixing", "dub",
        "performance", "advanced_is_mixing"])
class TestCategorizeToolTable:
    """Table-driven categorization cases (S2)."""

    def test_category(self, name, docstring, expected):
        from MCP_Server.docgen import categorize_tool
        assert categorize_tool(name, docstring) == expected
