#!/usr/bin/env python3
"""
POLISH SUITE - Professional Mix Finalization Tools

This suite provides the final polish pass for mixes generated by any of the
generators. It includes:
- Level balancing across tracks
- Stereo imaging optimization
- Frequency balancing suggestions
- Automation fine-tuning
- Export preparation

Usage:
    python scripts/polish_suite.py analyze          # Analyze current mix
    python scripts/polish_suite.py balance         # Balance track levels
    python scripts/polish_suite.py stereo          # Optimize stereo image
    python scripts/polish_suite.py automate        # Add basic automation
    python scripts/polish_suite.py export          # Prepare for export
    python scripts/polish_suite.py full            # Full polish pass
"""

import json
import socket
import math
import hashlib
from typing import Dict, Any, List, Tuple


class AbletonClient:
    """Client for Ableton Remote Script with caching."""
    
    def __init__(self, host="localhost", port=9877):
        self.host = host
        self.port = port
        self.socket = None
        self.cache = {}
    
    def connect(self):
        try:
            self.socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            self.socket.settimeout(30)
            self.socket.connect((self.host, self.port))
            return True
        except Exception as e:
            print(f"[CONNECT] Error: {e}")
            return False
    
    def send(self, cmd_type, params=None):
        if not self.socket and not self.connect():
            return None
        
        message = {"type": cmd_type, "params": params or {}}
        
        try:
            self.socket.sendall(json.dumps(message).encode() + b"\n")
            response = self.socket.recv(4096).decode()
            return json.loads(response) if response else {"status": "ok"}
        except Exception as e:
            self.socket = None
            return {"status": "error", "message": str(e)}
    
    def get_tracks(self):
        """Get all tracks with caching."""
        if "tracks" not in self.cache:
            result = self.send("get_all_tracks")
            if result and "result" in result:
                self.cache["tracks"] = result["result"].get("tracks", [])
        return self.cache.get("tracks", [])
    
    def get_master_track(self):
        """Get master track info."""
        return self.send("get_master_track")
    
    def get_scenes(self):
        """Get all scenes."""
        result = self.send("get_all_scenes")
        return result.get("result", {}).get("scenes", []) if result else []
    
    def get_tempo(self):
        """Get current tempo."""
        result = self.send("get_tempo")
        return result.get("result", {}).get("bpm", 120) if result else 120
    
    def close(self):
        try:
            if self.socket:
                self.socket.close()
        except:
            pass


class PolishEngine:
    """Core engine for mix polish operations."""
    
    TARGET_MAX_PEAK = -10.0  # dB - Headroom for mastering
    TARGET_RMS = -18.0  # dB - Good average level
    
    GENRE_PRESETS = {
        "dub": {
            "sub_bass_freq": 60,
            "bass_freq": 150,
            "mid_freq": 1000,
            "high_freq": 10000,
            "stereo_width": 0.7,
            "headroom_db": -12.0,
            "sub_boost_db": 3.0
        },
        "techno": {
            "sub_bass_freq": 50,
            "bass_freq": 120,
            "mid_freq": 2000,
            "high_freq": 12000,
            "stereo_width": 0.8,
            "headroom_db": -10.0,
            "sub_boost_db": 2.0
        },
        "house": {
            "sub_bass_freq": 55,
            "bass_freq": 130,
            "mid_freq": 1500,
            "high_freq": 11000,
            "stereo_width": 0.75,
            "headroom_db": -11.0,
            "sub_boost_db": 2.5
        },
        "hiphop": {
            "sub_bass_freq": 70,
            "bass_freq": 180,
            "mid_freq": 800,
            "high_freq": 8000,
            "stereo_width": 0.6,
            "headroom_db": -12.0,
            "sub_boost_db": 4.0
        },
        "default": {
            "sub_bass_freq": 60,
            "bass_freq": 150,
            "mid_freq": 1000,
            "high_freq": 10000,
            "stereo_width": 0.7,
            "headroom_db": -10.0,
            "sub_boost_db": 2.0
        }
    }
    
    def __init__(self, client):
        self.client = client
    
    def analyze_mix(self) -> Dict[str, Any]:
        """Perform comprehensive mix analysis."""
        print("\n[POLISH] Analyzing mix...")
        
        tracks = self.client.get_tracks()
        master = self.client.get_master_track()
        tempo = self.client.get_tempo()
        scenes = self.client.get_scenes()
        
        analysis = {
            "status": "success",
            "tracks": len(tracks),
            "scenes": len(scenes),
            "tempo": tempo,
            "track_analysis": [],
            "issues": [],
            "recommendations": []
        }
        
        # Analyze each track
        for i, track in enumerate(tracks):
            track_info = {
                "index": i,
                "name": track.get("name", f"Track {i}"),
                "volume_db": track.get("volume_db", 0),
                "pan": track.get("pan", 0),
                "type": self.detect_track_type(track),
                "is_armed": track.get("is_armed", False),
                "is_muted": track.get("is_muted", False),
                "is_soloed": track.get("is_soloed", False)
            }
            
            # Check for issues
            issues, recommendations = self.check_track_issues(track_info)
            track_info["issues"] = issues
            track_info["recommendations"] = recommendations
            
            analysis["track_analysis"].append(track_info)
            analysis["issues"].extend(issues)
            analysis["recommendations"].extend(recommendations)
        
        # Check master level
        master_info = master.get("result", {}) if isinstance(master, dict) else {}
        analysis["master_volume_db"] = master_info.get("volume_db", 0)
        
        if analysis["master_volume_db"] > -3.0:
            analysis["issues"].append("Master fader too high - may cause clipping")
            analysis["recommendations"].append("Reduce master fader to -6dB or lower")
        
        # Polish score (0-100)
        score = self.calculate_polish_score(analysis)
        analysis["polish_score"] = score
        
        print(f"[POLISH] Analysis complete - Score: {score}/100")
        
        return analysis
    
    def detect_track_type(self, track: Dict[str, Any]) -> str:
        """Detect track type based on name and characteristics."""
        name = track.get("name", "").lower()
        
        if any(x in name for x in ["kick", "drum", "percussion", "perc"]):
            return "drum"
        elif any(x in name for x in ["bass", "sub", "808"]):
            return "bass"
        elif any(x in name for x in ["vocal", "voice", "lead"]):
            return "vocal"
        elif any(x in name for x in ["piano", "keys", "synth", "pad", "chord", "melody"]):
            return "melody"
        elif any(x in name for x in ["effect", "fx", "ambient", "noise", "atmos"]):
            return "fx"
        return "other"
    
    def check_track_issues(self, track_info: Dict[str, Any]) -> Tuple[List[str], List[str]]:
        """Check track for potential issues."""
        issues = []
        recommendations = []
        
        name = track_info.get("name", "Track")
        vol = track_info["volume_db"]
        
        # Check volume
        if vol > -3.0:
            issues.append(f"Track '{name}' too loud ({vol:.1f}dB)")
            recommendations.append(f"Reduce '{name}' volume to -6dB to -3dB")
        
        if vol < -24.0:
            issues.append(f"Track '{name}' too quiet ({vol:.1f}dB)")
            recommendations.append(f"Increase '{name}' volume to -12dB or higher")
        
        # Check pan for mono tracks
        mono_types = ["drum", "bass"]
        if track_info["type"] in mono_types and abs(track_info["pan"]) > 0.3:
            recommendations.append(f"Consider centering '{name}' pan for better mono compatibility")
        
        # Check if muted
        if track_info["is_muted"]:
            issues.append(f"Track '{name}' is muted")
            recommendations.append(f"Unmute '{name}' or remove if not needed")
        
        # Check if armed but not recording
        if track_info["is_armed"] and track_info["type"] not in ["vocal", "drum"]:
            recommendations.append(f"Consider disarming '{name}' to save CPU")
        
        return issues, recommendations
    
    def calculate_polish_score(self, analysis: Dict[str, Any]) -> int:
        """Calculate polish score from 0-100."""
        score = 100
        
        # Penalize for issues
        score -= min(len(analysis["issues"]) * 5, 40)
        
        # Bonus for good practices
        master_vol = analysis.get("master_volume_db", 0)
        if master_vol < -4.0:
            score += 5
        
        # Check all tracks have reasonable volume
        for track in analysis["track_analysis"]:
            vol = track.get("volume_db", 0)
            if -18.0 <= vol <= -3.0:
                score += 2
            elif vol < -24.0 or vol > -1.0:
                score -= 3
        
        return min(max(score, 0), 100)
    
    def print_analysis(self, analysis: Dict[str, Any]):
        """Print analysis results in a readable format."""
        print("\n" + "=" * 70)
        print("MIX ANALYSIS REPORT")
        print("=" * 70)
        
        print(f"\n[SCORE] {analysis['polish_score']}/100")
        print(f"[TRACKS] {analysis['tracks']}")
        print(f"[SCENES] {analysis['scenes']}")
        print(f"[TEMPO] {analysis['tempo']} BPM")
        print(f"[MASTER] {analysis.get('master_volume_db', 0):.1f}dB")
        
        print("\n[TRACKS]")
        print("-" * 70)
        print(f"{'#':<3} {'Name':<20} {'Type':<10} {'Vol':<7} {'Pan':<6} {'Status'}")
        print("-" * 70)
        
        for track in analysis["track_analysis"]:
            status = []
            if track["is_muted"]:
                status.append("MUTED")
            elif track["is_soloed"]:
                status.append("SOLO")
            elif track["is_armed"]:
                status.append("ARMED")
            
            status_str = ", ".join(status) if status else "OK"
            print(f"{track['index']:<3} {track['name']:<20} {track['type']:<10} "
                  f"{track['volume_db']:>5.1f}dB {track['pan']:+5.1f} {status_str}")
        
        if analysis["issues"]:
            print("\n[ISSUES FOUND]")
            for i, issue in enumerate(analysis["issues"], 1):
                print(f"  {i}. {issue}")
        
        if analysis["recommendations"]:
            print("\n[RECOMMENDATIONS]")
            for i, rec in enumerate(analysis["recommendations"], 1):
                print(f"  {i}. {rec}")
        
        print("\n" + "=" * 70)
    
    def balance_levels(self, genre: str = None):
        """Balance track levels intelligently."""
        print("\n[POLISH] Balancing levels...")
        
        tracks = self.client.get_tracks()
        
        # Use genre-specific presets or defaults
        preset = self.GENRE_PRESETS.get(genre, self.GENRE_PRESETS["default"])
        
        # Target volumes for each track type
        target_volumes = {
            "drum": -4.0,
            "bass": -5.0,
            "vocal": -6.0,
            "melody": -7.0,
            "fx": -12.0,
            "other": -9.0
        }
        
        # Adjust for genre
        if genre == "dub":
            target_volumes["bass"] -= 1.0  # Bass louder for dub
            target_volumes["fx"] -= 3.0  # More echo/reverb
        elif genre == "techno":
            target_volumes["drum"] -= 2.0  # Louder kicks
            target_volumes["bass"] -= 1.0  # Louder bass
        elif genre == "house":
            target_volumes["melody"] -= 1.0  # Piano chords prominent
        elif genre == "hiphop":
            target_volumes["drum"] -= 1.0  # Punchy drums
            target_volumes["bass"] -= 2.0  # Heavy bass
        
        adjusted_count = 0
        for i, track in enumerate(tracks):
            track_type = self.detect_track_type(track)
            target_vol = target_volumes[track_type]
            
            # Get current volume
            current_vol = track.get("volume_db", 0)
            
            # Only adjust if significantly different
            if abs(current_vol - target_vol) > 2.0:
                self.client.send("set_track_volume", {
                    "track_index": i,
                    "volume_db": target_vol
                })
                print(f"  Track {i} ({track.get('name', '?')}): {current_vol:.1f}dB -> {target_vol:.1f}dB")
                adjusted_count += 1
        
        # Apply sub-bass boost for genres that need it
        if genre in ["dub", "hiphop", "techno", "house"]:
            for i, track in enumerate(tracks):
                if self.detect_track_type(track) == "bass":
                    current_vol = track.get("volume_db", -6.0)
                    new_vol = current_vol - preset.get("sub_boost_db", 2.0)
                    self.client.send("set_track_volume", {
                        "track_index": i,
                        "volume_db": new_vol
                    })
                    print(f"  Bass boost: Track {i} -> {new_vol:.1f}dB")
        
        print(f"[POLISH] Balanced {adjusted_count} tracks")
    
    def optimize_stereo_image(self):
        """Optimize stereo image for better spatialization."""
        print("\n[POLISH] Optimizing stereo image...")
        
        tracks = self.client.get_tracks()
        
        # Pan targets by type
        pan_targets = {
            "drum": [0.0, "center"],
            "bass": [0.0, "center"],
            "vocal": [0.0, "center"],
            "melody": [-0.3, "left"],
            "fx": [0.5, "right"],
            "other": [0.2, "slight right"]
        }
        
        for i, track in enumerate(tracks):
            track_type = self.detect_track_type(track)
            target_pan, position = pan_targets[track_type]
            
            current_pan = track.get("pan", 0.0)
            
            # Create deterministic but varied pan for each track
            track_id = f"{i}-{track_type}"
            hash_val = int(hashlib.md5(track_id.encode()).hexdigest(), 16)
            variation = (hash_val % 20 - 10) / 100.0  # -0.1 to +0.1
            final_pan = min(max(target_pan + variation, -1.0), 1.0)
            
            if abs(current_pan - final_pan) > 0.1:
                self.client.send("set_track_pan", {
                    "track_index": i,
                    "pan": final_pan
                })
                track_name = track.get('name', f'Track {i}')
                print(f"  {track_name}: pan {current_pan:.2f} -> {final_pan:.2f} ({position})")
        
        print("[POLISH] Stereo optimization complete")
    
    def add_basic_automation(self):
        """Add basic volume automation to selected tracks."""
        print("\n[POLISH] Adding basic automation...")
        
        tracks = self.client.get_tracks()
        scenes = self.client.get_scenes()
        
        if not scenes:
            print("[POLISH] No scenes found - skipping automation")
            return
        
        # Add automation points based on number of scenes
        points = []
        num_scenes = len(scenes)
        
        # Create automation points at scene boundaries
        for scene_idx in range(num_scenes):
            bar_position = scene_idx * 16  # Assume 16 bars per scene
            
            # Alternating volume for create interest
            mod = scene_idx % 4
            if mod == 0:
                volume = -3.0  # Slightly louder
            elif mod == 2:
                volume = -6.0  # Slightly quieter
            else:
                volume = -4.5  # Normal
            
            points.append({
                "bar": bar_position,
                "volume_db": volume,
                "curve": 2  # Linear
            })
        
        # Apply automation to FX tracks and melodies
        for i, track in enumerate(tracks):
            track_type = self.detect_track_type(track)
            if track_type in ["fx", "melody"]:
                track_name = track.get('name', f'Track {i}')
                print(f"  Adding automation to {track_name}")
                # Clear existing automation (if possible)
                self.client.send("clear_track_automation", {"track_index": i})
                
                # Add new automation points
                for point in points:
                    self.client.send("add_automation_point", {
                        "track_index": i,
                        "bar": point["bar"],
                        "volume_db": point["volume_db"],
                        "parameter": "volume"
                    })
        
        print("[POLISH] Automation added to relevant tracks")
    
    def prepare_for_export(self):
        """Prepare the mix for export."""
        print("\n[POLISH] Preparing for export...")
        
        tracks = self.client.get_tracks()
        
        # 1. Disarm all tracks to save CPU
        print("  Disarming all tracks...")
        for i in range(len(tracks)):
            self.client.send("set_track_arm", {"track_index": i, "arm": False})
        
        # 2. Ensure master is at safe level
        master = self.client.get_master_track()
        master_vol = master.get("result", {}).get("volume_db", 0) if isinstance(master, dict) else 0
        
        if master_vol > -6.0:
            self.client.send("set_master_volume", {"volume_db": -6.0})
            print(f"  Master volume adjusted to -6.0dB (was {master_vol:.1f}dB)")
        else:
            print(f"  Master volume OK at {master_vol:.1f}dB")
        
        # 3. Stop playback and return to start
        self.client.send("stop_playback")
        self.client.send("set_playhead_position", {"bar": 0, "beat": 0})
        
        # 4. Count ready tracks
        ready_count = sum(1 for t in tracks if t.get("has_clips", False))
        print(f"  {ready_count}/{len(tracks)} tracks have clips and are ready")
        
        print("[POLISH] Ready for export")
        print("  Note: Use Ableton's File -> Export Audio/Video...")
    
    def full_polish_pass(self, genre: str = None):
        """Perform complete polish pass."""
        print("\n" + "=" * 70)
        print("FULL POLISH PASS")
        print("=" * 70)
        
        # Step 1: Analyze
        print("\n[STEP 1/5] Analyzing mix...")
        analysis = self.analyze_mix()
        self.print_analysis(analysis)
        
        # Step 2: Balance
        print("\n[STEP 2/5] Balancing levels...")
        self.balance_levels(genre)
        
        # Step 3: Stereo
        print("\n[STEP 3/5] Optimizing stereo image...")
        self.optimize_stereo_image()
        
        # Step 4: Automation
        print("\n[STEP 4/5] Adding basic automation...")
        self.add_basic_automation()
        
        # Step 5: Export prep
        print("\n[STEP 5/5] Preparing for export...")
        self.prepare_for_export()
        
        # Final analysis
        print("\n[FINAL] Analyzing polished mix...")
        final_analysis = self.analyze_mix()
        
        improvement = final_analysis["polish_score"] - analysis["polish_score"]
        print(f"\n[RESULT] Polish score improved: {analysis['polish_score']} -> {final_analysis['polish_score']} (+{improvement})")
        
        print("\n" + "=" * 70)
        print("POLISH COMPLETE")
        print("=" * 70)
        print("\nNext: Export your mix from Ableton (File -> Export Audio/Video...)")


def main():
    """Main entry point."""
    import sys
    import os
    
    if len(sys.argv) < 2:
        print("Usage: python scripts/polish_suite.py <command> [options]")
        print("\nCommands:")
        print("  analyze          - Analyze current mix")
        print("  balance          - Balance track levels")
        print("  stereo           - Optimize stereo image")
        print("  automate         - Add basic automation")
        print("  export           - Prepare for export")
        print("  full [genre]     - Full polish pass (optional: specify genre)")
        print("\nGenres for full pass:")
        print("  dub, techno, house, hiphop")
        return
    
    command = sys.argv[1].lower()
    genre = sys.argv[2].lower() if len(sys.argv) > 2 else None
    
    client = AbletonClient()
    
    if not client.connect():
        print("[ERROR] Could not connect to Remote Script")
        return
    
    print("[OK] Connected to Remote Script")
    
    engine = PolishEngine(client)
    
    try:
        if command == "analyze":
            analysis = engine.analyze_mix()
            engine.print_analysis(analysis)
        
        elif command == "balance":
            engine.balance_levels(genre)
        
        elif command == "stereo":
            engine.optimize_stereo_image()
        
        elif command == "automate":
            engine.add_basic_automation()
        
        elif command == "export":
            engine.prepare_for_export()
        
        elif command == "full":
            engine.full_polish_pass(genre)
        
        else:
            print(f"[ERROR] Unknown command: {command}")
            print("Type 'python scripts/polish_suite.py' for usage")
    
    except Exception as e:
        print(f"\n[ERROR] {e}")
        import traceback
        traceback.print_exc()
    
    finally:
        client.close()


if __name__ == "__main__":
    main()
