"""Built-in seed recipes for the recipe library."""
import json
from typing import List, Dict, Any

BUILTIN_RECIPES: List[Dict[str, Any]] = [
    # ===== CHORD PROGRESSIONS (15) =====
    {"category": "chord_progression", "name": "Pop I-V-vi-IV", "tags": "pop,uplifting,verse",
     "description": "Classic pop progression: C G Am F.",
     "data": {"key": "C", "scale": "major", "chords": ["C", "G", "Am", "F"], "voicing": "open", "mood": "uplifting"}},
    {"category": "chord_progression", "name": "Deep House Seventh", "tags": "deep_house,warm,seventh",
     "description": "Smooth seventh loop: Am7 Dm7 G7 Cmaj7.",
     "data": {"key": "C", "scale": "major", "chords": ["Am7", "Dm7", "G7", "Cmaj7"], "voicing": "spread", "mood": "warm"}},
    {"category": "chord_progression", "name": "Techno Minor Loop", "tags": "techno,minimal,hypnotic",
     "description": "Hypnotic two-chord techno loop: Dm G.",
     "data": {"key": "D", "scale": "minor", "chords": ["Dm", "G"], "voicing": "close", "mood": "driving"}},
    {"category": "chord_progression", "name": "Dub Techno Pad", "tags": "dub_techno,ambient,space",
     "description": "Spacious dub techno: Dm G C F.",
     "data": {"key": "D", "scale": "minor", "chords": ["Dm", "G", "C", "F"], "voicing": "open", "mood": "spacious"}},
    {"category": "chord_progression", "name": "Ambient Drone", "tags": "ambient,drone,atmospheric",
     "description": "Slow-shifting ambient: Cmaj7 Fmaj9.",
     "data": {"key": "C", "scale": "major", "chords": ["Cmaj7", "Fmaj9"], "voicing": "spread", "mood": "atmospheric"}},
    {"category": "chord_progression", "name": "Jazz II-V-I", "tags": "jazz,swing,sophisticated",
     "description": "Essential jazz: Dm7 G7 Cmaj7.",
     "data": {"key": "C", "scale": "major", "chords": ["Dm7", "G7", "Cmaj7"], "voicing": "spread", "mood": "sophisticated"}},
    {"category": "chord_progression", "name": "Lo-Fi Dorian Loop", "tags": "lo-fi,dorian,chill",
     "description": "Warm lo-fi loop: Am7 D7 Am7 G.",
     "data": {"key": "A", "scale": "minor", "chords": ["Am7", "D7", "Am7", "G"], "voicing": "close", "mood": "chill"}},
    {"category": "chord_progression", "name": "Minimal Tech Stab", "tags": "minimal_tech,staccato,stab",
     "description": "Short stab chords: Eb7 D7.",
     "data": {"key": "Eb", "scale": "minor", "chords": ["Eb7", "D7"], "voicing": "close", "mood": "tense"}},
    {"category": "chord_progression", "name": "DnB Seventh Roll", "tags": "dnb,seventh,energetic",
     "description": "Fast-moving: Am7 Fmaj7 Cmaj7 G.",
     "data": {"key": "A", "scale": "minor", "chords": ["Am7", "Fmaj7", "Cmaj7", "G"], "voicing": "close", "mood": "energetic"}},
    {"category": "chord_progression", "name": "Trance Euphoric", "tags": "trance,euphoric,uplifting",
     "description": "Uplifting trance: Fm Db Ab Eb.",
     "data": {"key": "F", "scale": "minor", "chords": ["Fm", "Db", "Ab", "Eb"], "voicing": "spread", "mood": "euphoric"}},
    {"category": "chord_progression", "name": "Blues Shuffle", "tags": "blues,shuffle,gritty",
     "description": "12-bar blues: A7 D7 E7.",
     "data": {"key": "A", "scale": "major", "chords": ["A7", "D7", "E7"], "voicing": "open", "mood": "gritty"}},
    {"category": "chord_progression", "name": "Neo-Soul Voicing", "tags": "neo-soul,smooth,extended",
     "description": "Extended chords: Cm9 Fm9 G7#5 Cm9.",
     "data": {"key": "C", "scale": "minor", "chords": ["Cm9", "Fm9", "G7#5", "Cm9"], "voicing": "spread", "mood": "smooth"}},
    {"category": "chord_progression", "name": "Synthwave Arp", "tags": "synthwave,retro,driving",
     "description": "Retro synthwave: Am F C G.",
     "data": {"key": "A", "scale": "minor", "chords": ["Am", "F", "C", "G"], "voicing": "open", "mood": "driving"}},
    {"category": "chord_progression", "name": "Minimal Microtonal", "tags": "minimal,experimental,tense",
     "description": "Tension: C F G Ab.",
     "data": {"key": "C", "scale": "minor", "chords": ["C", "F", "G", "Ab"], "voicing": "close", "mood": "tense"}},
    {"category": "chord_progression", "name": "House Piano Loop", "tags": "house,piano,classic",
     "description": "Classic house: Fmaj7 G Em7 Am.",
     "data": {"key": "F", "scale": "major", "chords": ["Fmaj7", "G", "Em7", "Am"], "voicing": "open", "mood": "happy"}},

    # ===== DRUM PATTERNS (12) =====
    {"category": "drum_pattern", "name": "One Drop", "tags": "dub,reggae,classic",
     "description": "Classic dub reggae: kick beat 1, snare beat 3 delayed.",
     "data": {"pattern_type": "one_drop", "kit_query": "query:Drums#FileId_58622", "bars": 4,
              "grid": "|X---|----|--X-|----|", "tempo_range": [70, 90], "mood": "dub"}},
    {"category": "drum_pattern", "name": "Rockers", "tags": "reggae,skank,offbeat",
     "description": "Jamaican rockers: offbeat emphasis.",
     "data": {"pattern_type": "rockers", "kit_query": "query:Drums#FileId_58622", "bars": 4,
              "grid": "|X-X-|---|X-X-|---|", "tempo_range": [75, 95], "mood": "groovy"}},
    {"category": "drum_pattern", "name": "Steppers", "tags": "dub,steppers,driving",
     "description": "Even kick distribution, minimal variation.",
     "data": {"pattern_type": "steppers", "kit_query": "query:Drums#FileId_58622", "bars": 4,
              "grid": "|X---|X---|X---|X---|", "tempo_range": [80, 100], "mood": "driving"}},
    {"category": "drum_pattern", "name": "House Basic", "tags": "house,four_on_floor,clap",
     "description": "Four-on-the-floor with clap on 2 and 4.",
     "data": {"pattern_type": "house_basic", "kit_query": "query:Drums#FileId_58622", "bars": 4,
              "grid": "|X---|---|X---|---|", "tempo_range": [120, 130], "mood": "driving"}},
    {"category": "drum_pattern", "name": "Techno 4x4", "tags": "techno,driving,relentless",
     "description": "Driving techno: continuous kick.",
     "data": {"pattern_type": "techno_4x4", "kit_query": "query:Drums#FileId_58622", "bars": 4,
              "grid": "|X---|X---|X---|X---|", "tempo_range": [125, 145], "mood": "relentless"}},
    {"category": "drum_pattern", "name": "Dub Techno", "tags": "dub_techno,syncopated,spacious",
     "description": "Syncopated dub techno: offbeat accents.",
     "data": {"pattern_type": "dub_techno", "kit_query": "query:Drums#FileId_58622", "bars": 4,
              "grid": "|X---|----|--X-|----|", "tempo_range": [70, 90], "mood": "spacious"}},
    {"category": "drum_pattern", "name": "Half Time", "tags": "half_time,heavy,slowed",
     "description": "Half-time feel: heavy kick and snare placement.",
     "data": {"pattern_type": "steppers", "kit_query": "query:Drums#FileId_58622", "bars": 4,
              "grid": "|X---|---X---|---X---|---X---|", "tempo_range": [80, 100], "mood": "heavy"}},
    {"category": "drum_pattern", "name": "Shuffle", "tags": "shuffle,swing,groovy",
     "description": "Swing-shuffle: triplet-feel hi-hats.",
     "data": {"pattern_type": "rockers", "kit_query": "query:Drums#FileId_58622", "bars": 4,
              "grid": "|X-X-|X-X-|X-X-|X-X-|", "tempo_range": [90, 120], "mood": "groovy"}},
    {"category": "drum_pattern", "name": "Breakbeat Core", "tags": "breakbeat,dnb,chopped",
     "description": "Amen-style: syncopated kicks, rapid snares.",
     "data": {"pattern_type": "one_drop", "kit_query": "query:Drums#FileId_58622", "bars": 2,
              "grid": "|X--X|-X-X|X--X|--X-|", "tempo_range": [160, 180], "mood": "energetic"}},
    {"category": "drum_pattern", "name": "Footwork", "tags": "footwork,frenetic,triple_time",
     "description": "Fast footwork: triple-time hats, rolling kicks.",
     "data": {"pattern_type": "techno_4x4", "kit_query": "query:Drums#FileId_58622", "bars": 4,
              "grid": "|X-X-|X-X-|X-X-|X-X-|", "tempo_range": [150, 170], "mood": "frenetic"}},
    {"category": "drum_pattern", "name": "Trap", "tags": "trap,hip-hop,heavy_hihat",
     "description": "Modern trap: heavy 808, syncopated hats.",
     "data": {"pattern_type": "steppers", "kit_query": "query:Drums#FileId_58622", "bars": 4,
              "grid": "|X---|-X--|--X-|-X-X|", "tempo_range": [70, 80], "mood": "aggressive"}},
    {"category": "drum_pattern", "name": "Soca", "tags": "soca,carnival,energetic",
     "description": "Soca kick-snare: driving upbeat energy.",
     "data": {"pattern_type": "house_basic", "kit_query": "query:Drums#FileId_58622", "bars": 4,
              "grid": "|X---|X---|X---|X---|", "tempo_range": [110, 130], "mood": "energetic"}},

    # ===== MIX TEMPLATES (10) =====
    {"category": "mix_template", "name": "Deep House", "tags": "house,warm,melodic",
     "description": "Warm deep house: extended breakdown, gradual build.",
     "data": {"genre": "deep_house", "track_count": 6,
              "structure": ["intro", "groove_a", "build", "drop", "breakdown", "groove_b", "outro"],
              "mixing_techniques": ["bass_forward", "crossfade", "filter_sweep", "send_sweep", "strip_and_build"],
              "energy_curve": "progressive_house"}},
    {"category": "mix_template", "name": "Techno", "tags": "techno,driving,minimal",
     "description": "Relentless techno: fast transitions, minimal breakdowns.",
     "data": {"genre": "techno", "track_count": 6,
              "structure": ["groove_a", "groove_b", "build", "drop", "groove_a", "outro"],
              "mixing_techniques": ["filter_sweep", "crossfade", "volume_automation", "filter_sweep"],
              "energy_curve": "plateau"}},
    {"category": "mix_template", "name": "Dub Techno", "tags": "dub,techno,spacious",
     "description": "Spacious dub techno: long reverb, slow evolution.",
     "data": {"genre": "dub_techno", "track_count": 5,
              "structure": ["intro", "groove_a", "groove_b", "groove_a", "groove_c", "outro"],
              "mixing_techniques": ["bass_forward", "send_sweep", "dub_drop", "crossfade"],
              "energy_curve": "dub_techno"}},
    {"category": "mix_template", "name": "Ambient", "tags": "ambient,slow,evolving",
     "description": "Slow ambient: 16+ bar sections, gradual pad crossfades.",
     "data": {"genre": "ambient", "track_count": 4,
              "structure": ["intro", "groove_a", "groove_b", "groove_c", "outro"],
              "mixing_techniques": ["crossfade", "volume_automation", "send_sweep"],
              "energy_curve": "ambient"}},
    {"category": "mix_template", "name": "Pop", "tags": "pop,verse_chorus,structured",
     "description": "Standard pop: clear verse-chorus structure.",
     "data": {"genre": "pop", "track_count": 7,
              "structure": ["intro", "groove_a", "build", "drop", "groove_b", "build_2", "drop", "outro"],
              "mixing_techniques": ["strip_and_build", "filter_sweep", "crossfade", "volume_automation"],
              "energy_curve": "progressive_house"}},
    {"category": "mix_template", "name": "Drum & Bass", "tags": "dnb,fast,energetic",
     "description": "High-energy DnB: short sections, rapid-fire mixing.",
     "data": {"genre": "dnb", "track_count": 6,
              "structure": ["groove_a", "build", "drop", "groove_b", "build_2", "drop", "outro"],
              "mixing_techniques": ["crossfade", "filter_sweep", "bass_forward", "volume_automation"],
              "energy_curve": "driving"}},
    {"category": "mix_template", "name": "Minimal", "tags": "minimal,reductive,space",
     "description": "Less is more: few elements, maximum groove.",
     "data": {"genre": "minimal", "track_count": 4,
              "structure": ["groove_a", "groove_a", "build", "groove_b", "groove_a"],
              "mixing_techniques": ["filter_sweep", "crossfade", "volume_automation", "crossfade"],
              "energy_curve": "minimal"}},
    {"category": "mix_template", "name": "Hip-Hop", "tags": "hip-hop,verse_hook,bounce",
     "description": "Beat-driven hip-hop with drop-ins and cuts.",
     "data": {"genre": "hip-hop", "track_count": 6,
              "structure": ["intro", "groove_a", "groove_b", "groove_a", "groove_c", "outro"],
              "mixing_techniques": ["strip_and_build", "bass_forward", "crossfade", "dub_drop"],
              "energy_curve": "progressive_house"}},
    {"category": "mix_template", "name": "Lo-Fi", "tags": "lo-fi,chill,warm",
     "description": "Relaxed lo-fi: tape warmth, subtle movement.",
     "data": {"genre": "lo-fi", "track_count": 4,
              "structure": ["intro", "groove_a", "groove_b", "groove_a", "outro"],
              "mixing_techniques": ["crossfade", "send_sweep", "volume_automation"],
              "energy_curve": "ambient"}},
    {"category": "mix_template", "name": "Trance", "tags": "trance,euphoric,long_build",
     "description": "Classic trance: 32-bar builds, euphoric drops.",
     "data": {"genre": "trance", "track_count": 7,
              "structure": ["intro", "groove_a", "build", "drop", "breakdown", "build_2", "drop", "outro"],
              "mixing_techniques": ["filter_sweep", "strip_and_build", "crossfade", "send_sweep", "volume_automation"],
              "energy_curve": "progressive_house"}},

    # ===== SOUND DESIGN PRESETS (13) =====
    {"category": "sound_design", "name": "Deep Sub Bass", "tags": "bass,sub,minimal",
     "description": "Pure sine sub-bass, 48 Hz fundamental.",
     "data": {"device_type": "Operator", "preset_name": "Deep Sub Bass",
              "parameters": {"osc1_coarse": 48, "osc1_level": -6, "filter_cutoff": 0.3, "filter_resonance": 0.1, "volume": -3},
              "tags": ["bass", "sub", "minimal"]}},
    {"category": "sound_design", "name": "Warm Reese Bass", "tags": "bass,reese,warm",
     "description": "Detuned sawtooth reese: two oscillators, low-passed.",
     "data": {"device_type": "Operator", "preset_name": "Warm Reese Bass",
              "parameters": {"osc1_coarse": 36, "osc2_coarse": 36, "osc2_detune": 7,
                            "filter_cutoff": 0.45, "filter_resonance": 0.3, "volume": -6},
              "tags": ["bass", "reese", "dnb"]}},
    {"category": "sound_design", "name": "FM Pluck Bass", "tags": "bass,fm,pluck",
     "description": "FM pluck: fast decay, metallic attack.",
     "data": {"device_type": "Operator", "preset_name": "FM Pluck Bass",
              "parameters": {"osc1_coarse": 48, "algorithm": 2, "filter_cutoff": 0.6, "filter_resonance": 0.15,
                            "envelope_attack": 0.005, "envelope_decay": 0.3, "volume": -4},
              "tags": ["bass", "fm", "pluck"]}},
    {"category": "sound_design", "name": "Atmospheric Pad", "tags": "pad,atmospheric,wide",
     "description": "Wide analog pad: sawtooth, chorus, reverb.",
     "data": {"device_type": "Analog", "preset_name": "Atmospheric Pad",
              "parameters": {"osc1_waveform": "saw", "osc2_waveform": "saw", "osc2_detune": 5,
                            "filter_cutoff": 0.5, "filter_resonance": 0.2, "chorus_amount": 0.6, "reverb_amount": 0.4, "volume": -8},
              "tags": ["pad", "atmospheric", "wide"]}},
    {"category": "sound_design", "name": "Analog Brass", "tags": "brass,synth,warm",
     "description": "Synthetic brass: saw waves, moderately open filter.",
     "data": {"device_type": "Analog", "preset_name": "Analog Brass",
              "parameters": {"osc1_waveform": "saw", "osc2_waveform": "saw", "osc2_detune": 2,
                            "filter_cutoff": 0.7, "filter_resonance": 0.25, "envelope_attack": 0.05, "envelope_release": 0.3, "volume": -5},
              "tags": ["brass", "synth", "warm"]}},
    {"category": "sound_design", "name": "Wavetable Lead", "tags": "lead,wavetable,bright",
     "description": "Bright wavetable lead with position modulation.",
     "data": {"device_type": "Wavetable", "preset_name": "Wavetable Lead",
              "parameters": {"wavetable_position": 0.3, "wavetable_mod_rate": 0.2, "wavetable_mod_depth": 0.4,
                            "filter_cutoff": 0.75, "filter_resonance": 0.1, "volume": -5},
              "tags": ["lead", "wavetable", "bright"]}},
    {"category": "sound_design", "name": "Electric Piano", "tags": "keys,ep,warm",
     "description": "FM electric piano: bell-like attack, warm body.",
     "data": {"device_type": "Electric", "preset_name": "Electric Piano",
              "parameters": {"tine_harmonics": 0.6, "hammer_noise": 0.2, "pickup_position": 0.5,
                            "filter_cutoff": 0.6, "volume": -4},
              "tags": ["keys", "electric_piano", "warm"]}},
    {"category": "sound_design", "name": "808 Sub", "tags": "808,bass,trap",
     "description": "808 sub: long decay, sine fundamental.",
     "data": {"device_type": "Operator", "preset_name": "808 Sub",
              "parameters": {"osc1_coarse": 36, "filter_cutoff": 0.25,
                            "envelope_attack": 0.0, "envelope_decay": 1.5, "envelope_sustain": 0.0, "envelope_release": 0.5, "volume": -2},
              "tags": ["bass", "808", "trap"]}},
    {"category": "sound_design", "name": "FM Bell", "tags": "bell,fm,metallic",
     "description": "Inharmonic FM bell: metallic attack, long decay.",
     "data": {"device_type": "Operator", "preset_name": "FM Bell",
              "parameters": {"algorithm": 8, "osc1_coarse": 52, "osc2_ratio": 14.5,
                            "filter_cutoff": 0.8, "envelope_attack": 0.0, "envelope_decay": 2.0, "volume": -6},
              "tags": ["bell", "fm", "metallic"]}},
    {"category": "sound_design", "name": "Deep House Pluck", "tags": "pluck,deep_house,soft",
     "description": "Soft pluck: short decay, warm low-pass.",
     "data": {"device_type": "Operator", "preset_name": "Deep House Pluck",
              "parameters": {"osc1_coarse": 48, "osc1_level": -3, "filter_cutoff": 0.5, "filter_resonance": 0.2,
                            "envelope_attack": 0.01, "envelope_decay": 0.4, "envelope_sustain": 0.0, "chorus_amount": 0.3, "volume": -5},
              "tags": ["pluck", "house", "soft"]}},
    {"category": "sound_design", "name": "Riser FX", "tags": "fx,riser,build_up",
     "description": "Tension-building riser: filter sweep, noise layer.",
     "data": {"device_type": "Operator", "preset_name": "Riser FX",
              "parameters": {"osc1_waveform": "noise", "filter_type": "highpass", "filter_cutoff": 0.1,
                            "pitch_bend_range": 12, "envelope_attack": 4.0, "envelope_sustain": 1.0, "volume": -10},
              "tags": ["fx", "riser", "build"]}},
    {"category": "sound_design", "name": "PWM String Pad", "tags": "pad,string,pwm",
     "description": "Pulse-width modulated strings: evolving, cinematic.",
     "data": {"device_type": "Analog", "preset_name": "PWM String Pad",
              "parameters": {"osc1_waveform": "pulse", "osc2_waveform": "pulse", "osc2_detune": 3,
                            "pulse_width": 0.3, "pwm_rate": 0.15, "pwm_depth": 0.5,
                            "filter_cutoff": 0.45, "filter_resonance": 0.3, "reverb_amount": 0.5, "volume": -8},
              "tags": ["pad", "string", "pwm"]}},
    {"category": "sound_design", "name": "Tape Saturation", "tags": "effect,tape,saturation,warmth",
     "description": "Tape-style saturation: subtle warmth, harmonic enhancement.",
     "data": {"device_type": "Saturator", "preset_name": "Tape Warmth",
              "parameters": {"drive": 0.3, "saturation_type": "tape", "frequency": 1000, "tone": 0.5, "volume": -1},
              "tags": ["effect", "tape", "saturation"]}},
]


def get_builtin_recipes():
    """Return built-in recipes with data serialized to JSON strings."""
    result = []
    for recipe in BUILTIN_RECIPES:
        entry = dict(recipe)
        entry["data"] = json.dumps(recipe["data"])
        result.append(entry)
    return result
